from __future__ import annotations

from dash import dcc, html
import dash_mantine_components as dmc
from dash_iconify import DashIconify
from components.brand import ROSCA_BLUE, ROSCA_GREEN, ROSCA_NAVY, ROSCA_SLATE, ROSCA_TEXT, brand_lockup, mark

PALETTE=[
("ROSCA Blue",ROSCA_BLUE,"#0E68FF","Primary action / focus"),
("Deep Navy",ROSCA_NAVY,"#0F172A","Brand foundation / dark UI"),
("Industrial Slate",ROSCA_SLATE,"#1E293B","Panels / surfaces"),
("Technical Mist",ROSCA_TEXT,"#CBD5E1","Technical text"),
("Signal Green",ROSCA_GREEN,"#22C55E","Success / validation"),
]

def swatch(name,color,hex_value,use):
    return dmc.Paper(dmc.Stack([html.Div(style={"height":"72px","borderRadius":"8px","background":color}),dmc.Text(name,fw=800,size="sm"),dmc.Text(hex_value,ff="monospace",size="xs",c="blue"),dmc.Text(use,size="xs",c="dimmed")],gap=4),withBorder=True,p="sm",radius="md")

def identity_page():
    return dmc.Stack([
        dmc.Group([dmc.Stack([dmc.Text("BRAND SYSTEM",size="xs",fw=900,c="blue",style={"letterSpacing":".18em"}),dmc.Title("ROSCA visual identity",order=1),dmc.Text("Proposta 3 · Robusta · Industrial · Tecnológica",size="md",c="dimmed")],gap=3),dmc.Group([dcc.Link(dmc.Button("Developer Design System",leftSection=DashIconify(icon="tabler:code",width=17),variant="subtle",color="gray"),href="/design-system",refresh=False),dmc.Button("Baixar identidade visual",id="download-identity",leftSection=DashIconify(icon="tabler:download",width=17),color="blue")],gap="xs")],justify="space-between",align="flex-start"),
        dmc.Paper([dmc.Group([brand_lockup(58),dmc.Badge("ENGINEERING INTELLIGENCE",color="blue",variant="light",size="lg")],justify="space-between"),dmc.Text("Robusta · Industrial · Tecnológica",size="xl",fw=700,mt="xl"),dmc.Text("Uma identidade construída a partir de geometria, precisão e leitura técnica. O símbolo combina a inicial R com uma moldura hexagonal para representar peça, seção, estrutura e engenharia.",size="md",c="dimmed",maw=800,mt="xs"),dmc.Group([dmc.Badge("GEOMETRIA",color="blue",variant="filled"),dmc.Badge("PRECISÃO",color="blue",variant="light"),dmc.Badge("INTELIGÊNCIA",color="green",variant="light")],mt="md")],withBorder=True,p="xl",radius="md",className="identity-hero"),
        dmc.Grid([dmc.GridCol(dmc.Paper([dmc.Text("01 · SÍMBOLO",size="xs",fw=900,c="blue",style={"letterSpacing":".14em"}),dmc.Center(mark(190),style={"minHeight":"245px"}),dmc.Text("R + geometria hexagonal",fw=800,ta="center"),dmc.Text("O hexágono sugere estrutura e precisão industrial; o R cria reconhecimento imediato para ROSCA.",size="sm",c="dimmed",ta="center")],withBorder=True,p="xl",radius="md"),span={"base":12,"md":5}),dmc.GridCol(dmc.Paper([dmc.Text("02 · WORDMARK",size="xs",fw=900,c="blue",style={"letterSpacing":".14em"}),dmc.Center(brand_lockup(72),style={"minHeight":"245px"}),dmc.Divider(my="md"),dmc.Text("ROSCA",fw=900,size="34px",style={"letterSpacing":".075em"}),dmc.Text("ENGINEERING INTELLIGENCE",fw=700,size="sm",c="blue",style={"letterSpacing":".11em"}),dmc.Text("A assinatura reforça o posicionamento como inteligência aplicada à engenharia.",size="sm",c="dimmed",mt="xs")],withBorder=True,p="xl",radius="md"),span={"base":12,"md":7})],gutter="md"),
        dmc.Stack([dmc.Group([dmc.Title("03 · PALETA CROMÁTICA",order=2),dmc.Text("Contraste técnico + sinalização funcional",size="sm",c="dimmed")],justify="space-between"),dmc.SimpleGrid([swatch(*item) for item in PALETTE],cols={"base":1,"xs":2,"lg":5},spacing="sm")],gap="sm"),
        dmc.Grid([dmc.GridCol(dmc.Paper([dmc.Text("04 · TIPOGRAFIA",size="xs",fw=900,c="blue",style={"letterSpacing":".14em"}),dmc.Text("Montserrat",size="36px",fw=800,mt="md"),dmc.Text("Marca, títulos e destaque",size="sm",c="dimmed"),dmc.Divider(my="md"),dmc.Text("Inter",size="28px",fw=600),dmc.Text("Interface, dados, controles e textos",size="sm",c="dimmed"),dmc.Text("Aa 0123456789 → % Ø α1 α2",ff="monospace",mt="md",c="blue")],withBorder=True,p="lg",radius="md"),span={"base":12,"md":6}),dmc.GridCol(dmc.Paper([dmc.Text("05 · ICONOGRAFIA",size="xs",fw=900,c="blue",style={"letterSpacing":".14em"}),dmc.Title("Tabler / Iconify",order=3,mt="xs"),dmc.Text("Ícones lineares, técnicos e consistentes. Cada ícone representa uma ação, ferramenta ou estado.",size="sm",c="dimmed"),dmc.Group([dmc.Stack([dmc.ThemeIcon(DashIconify(icon=i),color="green" if n in {"Validate","Export"} else "blue",variant="light",size="lg"),dmc.Text(n,size="xs",fw=700)],gap=4) for i,n in [("tabler:adjustments","Define"),("tabler:shield-check","Validate"),("tabler:player-play","Simulate"),("tabler:search","Inspect"),("tabler:ruler-measure","Measure"),("tabler:file-export","Export")]],gap="lg",mt="md")],withBorder=True,p="lg",radius="md"),span={"base":12,"md":6})],gutter="md"),
        dmc.Paper([dmc.Group([dmc.Title("06 · APLICAÇÃO NA INTERFACE",order=2),dmc.Badge("ROSCA UI",color="blue",variant="filled")],justify="space-between"),dmc.SimpleGrid([dmc.Stack([dmc.Text("01",c="blue",fw=900),dmc.Text("Navegação",fw=800),dmc.Text("Navy como estrutura; azul técnico para foco e ação.",size="sm",c="dimmed")],gap=4),dmc.Stack([dmc.Text("02",c="blue",fw=900),dmc.Text("Análise",fw=800),dmc.Text("Superfícies escuras e dados em primeiro plano.",size="sm",c="dimmed")],gap=4),dmc.Stack([dmc.Text("03",c="green",fw=900),dmc.Text("Estados",fw=800),dmc.Text("Verde confirma sucesso; âmbar pede revisão; vermelho bloqueia.",size="sm",c="dimmed")],gap=4),dmc.Stack([dmc.Text("04",c="blue",fw=900),dmc.Text("Interação",fw=800),dmc.Text("Controles compactos e ícones lineares reforçam o fluxo.",size="sm",c="dimmed")],gap=4)],cols={"base":1,"sm":2,"lg":4},mt="md")],withBorder=True,p="lg",radius="md"),
        dmc.Paper([dmc.Group([dmc.Stack([dmc.Text("PARA DESENVOLVEDORES",size="xs",fw=900,c="blue",style={"letterSpacing":".14em"}),dmc.Title("Implementação da identidade",order=3),dmc.Text("Tokens, componentes, ícones, layout e acessibilidade documentados para implementação.",size="sm",c="dimmed")],gap=3),dcc.Link(dmc.Button("Abrir documentação",rightSection=DashIconify(icon="tabler:arrow-right",width=16),variant="light",color="blue"),href="/design-system",refresh=False)],justify="space-between")],withBorder=True,p="lg",radius="md")
    ],gap="md",className="identity-page")
